# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fd1c96304df2d3ab5dcba8a3789ca0aa4c1aee77456db522496ca3f3d14ef7e1b8aaeb7b8eb3690fca5b0b85fd0c447a92f10a252625d4e0811494ec8e2ff0c

test:
  secret_key_base: f9f1c91c2fd3a92081198345b725650f959e5cdfa56fa7884c583a6081a69d607f5d9812f77f3a9323ef73663002067c0c9c27c03d6e1f4e9d60162968457301

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
